# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_corp_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corp',
            name='slug',
        ),
    ]
