# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_corp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
