# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-18 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20170517_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
